# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: false

# Setup
title:            'Jakub Prüher'
tagline:          'PhD student'
description:      'A blog of a man with common sense.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jakub Prüher'
  url:            <my url here>

paginate:         5

# Custom vars
# version:          2.1.0

# github:           
  # repo:           https://github.com/jacobnzw

# Gems
gems: [jekyll-paginate, jekyll-gist, 'jekyll/scholar']
